FROM debian:buster

ENV FLANNEL_ARCH=amd64

RUN apt-get update && apt-get install -y net-tools ca-certificates iptables strongswan && update-ca-certificates

COPY dist/flanneld-$FLANNEL_ARCH /opt/bin/flanneld
COPY dist/mk-docker-opts.sh /opt/bin

ENTRYPOINT ["/opt/bin/flanneld"]
